### ISSUE TITLE
fix home screen styles

### ISSUE THREAD

**Issue by MasterBrian99** [MasterBrian99/tailwind-item-collection#2]

**Comment by RajMhatre20** [comment]
I would like to work on this issue

**Comment by MasterBrian99** [comment]
go ahead !!

**Comment by RajMhatre20** [comment]
I'm not able to complete it because there's an error in compiling process whenever I try to start the app it shows there's no default export for Routes, when I go in the Routes folder there's error in routeURL regarding casing, I tried debugging it but found no solution. sorry

**Comment by MasterBrian99** [comment]
can you send me the console error ? i am unable to reproduce this error ?

**Comment by RajMhatre20** [comment]
```
Failed to compile.

./src/App.tsx
Cannot find file: 'Routes.ts' does not match the corresponding name on disk: '.\src\router\routes.ts'.
```

What I did was first forked the repo to my local machine(os: windows 11) then ran ```npm install``` then ```npm start```. I think conflict is due to the same name of both file in the router folder

**Comment by MasterBrian99** [comment]
fixed it.i accidentally created 2 files with same file name.

**Comment by RajMhatre20** [comment]
Thank you. I think it's now working fine. I'll try to work on it again.

**Comment by RajMhatre20** [comment]
Can you help me understanding the CSS where it's coming from? for e.g. in screens/MainScreen.tsx div has className="h-screen main-backdrop"  where are these styles fetched from?

**Comment by RajMhatre20** [comment]
Got it, thanks
